// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function reducer(state, action) {
  if (action) {
    return state - 1 | 0;
  } else {
    return state + 1 | 0;
  }
}

function App(Props) {
  var match = React.useReducer(reducer, 0);
  var dispatch = match[1];
  return React.createElement("div", undefined, React.createElement("p", undefined, "Counter:" + String(match[0])), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Increment */0);
                    })
                }, "Increment"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Decrement */1);
                    })
                }, "Decrement"));
}

var state = 0;

var make = App;

exports.reducer = reducer;
exports.state = state;
exports.make = make;
/* react Not a pure module */
