// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var NumberFormat = {};

var formatId = new (Intl.NumberFormat)("id-ID");

var formatId2 = new (Intl.NumberFormat)("id-ID", {
      style: "currency",
      currency: "IDR"
    });

var limaribu = formatId.format(500000.0);

var limaribu2 = formatId2.format(9999.9);

console.log("with pipe", formatId2.format(10000));

console.log("hey", formatId2.format(10000));

console.log(limaribu, "<--");

console.log(limaribu2, "<-|");

var intNumber = 10000;

exports.NumberFormat = NumberFormat;
exports.formatId = formatId;
exports.formatId2 = formatId2;
exports.limaribu = limaribu;
exports.limaribu2 = limaribu2;
exports.intNumber = intNumber;
/* formatId Not a pure module */
