// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function add(x, y) {
  return x + y | 0;
}

function addFloat(x, y) {
  return x + y;
}

exports.add = add;
exports.addFloat = addFloat;
/* No side effect */
