// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function add(x, y) {
  return x + y | 0;
}

function sub(x, y) {
  return x - y | 0;
}

console.log(30);

console.log(-5);

console.log(5);

function not(n) {
  if (n === 0) {
    return 1;
  } else {
    return Math.imul(n, not(n - 1 | 0));
  }
}

console.log("Custom Operator {|+}", 65);

console.log("Custom Operator {|-}", 5);

console.log("Custom Operator {|-}", -5);

console.log("Custom Operator {!4}", not(4));

console.log("Custom Operator {!4}", not(10));

var mynum = 30;

var $pipe$plus = add;

var $pipe$neg = sub;

exports.add = add;
exports.sub = sub;
exports.mynum = mynum;
exports.$pipe$plus = $pipe$plus;
exports.$pipe$neg = $pipe$neg;
exports.not = not;
/*  Not a pure module */
